### ISSUE TITLE
Error reported by XML parser: Content ist nicht zulässig in Prolog.

### ISSUE THREAD

**Issue by Neon82** [gatling/gatling-academy-module-2-java#23]
Hi I just installed Gattling via Maven computer Database runs fine affter adding the demostor C9 and tryed to run this I get "Error reported by XML parser: Content ist nicht zulässig in Prolog." is there an error in the file or do i miss something? Java is on version 11.0.16.1

**Comment by Isammoc** [comment]
Indeed. I just reproduced.

Steps:

```console
git clone https://github.com/gatling/gatling-academy-module-2-java.git
cd gatling-academy-module-2-java
mvn gatling:test
```

Explanation:
The issue is that HTML returned by the server is not a valid XML and during the refactoring (between C8 and C9) some `css` check were transformed into `xpath` check.

Workaround:
Put back the `css` check

@Neon82 Can you contribute a fix?

**Comment by slandelle** [comment]
I've just fixed it and also upgrading the dependencies versions.
Thanks again for reporting!
