### ISSUE TITLE
status.find.in([200, 209], 304), found 500 

### ISSUE THREAD

**Issue by Neon82** [gatling/gatling-academy-module-2-java#24]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/68306267/205588585-b5000134-f713-4d01-a1af-a8f729df921e.png">
downloaded the updated version, there is is on check wrong^^ see screenshot

**Comment by slandelle** [comment]
@Neon82 Thanks a lot for reporting! Actually, the issue was that the url was wrong in the test.
